### PR TITLE
Gelasio update

### PR DESCRIPTION
**Pull request by emmamarichal**
Hi @EbenSorkin,

Here you can find the fonts exported. As I said here https://github.com/google/fonts/issues/6869#issuecomment-1899987469, there is no kerning and I wanted to know if you wanted to add some, from Georgia for example?

In any case, you can merge this PR, and if we keep it without any kerning, I'll try to send a PR to the GF repo today!

Thanks!

### CODE REVIEW

**Comment by EbenSorkin** [comment]
Curiously both verdana and Georgia were made without kerning - on purpose.
So we would break metric compatibility if we added it. If that’s our only
issue we can push to live now I think.

**Comment by emmamarichal** [comment]
@EbenSorkin great! then you can merge that PR, thanks :)

**Comment by emmamarichal** [comment]
@EbenSorkin could you merge that PR? :) thanks!

**Comment by EbenSorkin** [comment]
I’ll see if I can do it today. Thanks for the reminder. I think I must have
missed the pr request

**Comment by EbenSorkin** [comment]
Done.

**Pull request merged**
